apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "11"
  params:
    # - name: dockerfile
    #   value: ./docker-example/Dockerfile
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/odedia/tanzu-java-web-app
      ref:
        branch: main
  